language: node_js
version: 1.0
node_js:
    - "node"
script:
    - echo "skipping tests"
deploy:
  edge: true
  provider: npm
  email: weiss.dennis98@yahoo.de
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
    skip_cleanup: true
